test alternative approach

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -42,7 +42,7 @@ jobs:
       - name: Install Python dependencies
         run: |
           python -m pip install --upgrade pip
-          python -m pip install build setuptools wheel twine
+          python -m pip install build setuptools wheel twine cibuildwheel
 
       - name: Build C extension
         run: |
@@ -52,6 +52,15 @@ jobs:
         if: runner.os == 'Linux'
         run: |
           # note default output dir after repair: wheelhouse
+          python -m cibuildwheel --platform linux
           python -m pip install auditwheel 
           python -m auditwheel show dist/*.whl
           python -m auditwheel repair dist/*whl
+          
+      - name: Publish to Test PyPI
+        if: false
+        run: |
+          twine --repository testpypi upload dist/* || { echo "::error:: ❌ Error: Upload failed. Possibly because the version already exists."; exit 1; }
+        env:
+          TWINE_USERNAME: __token__
+          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_API_TOKEN_ENV }}
