lets test the upload

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -21,7 +21,6 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
 
-
       - name: Install system dependencies (Ubuntu)
         if: runner.os == 'Linux'
         run: |
@@ -44,22 +43,20 @@ jobs:
           python -m pip install --upgrade pip
           python -m pip install build setuptools wheel twine cibuildwheel
 
-      - name: Build C extension
+      - name: Build C extension (common python build)
         if: runner.os == 'Windows' || runner.os == 'macOS'
         run: |
           python -m build --wheel
 
-      - name: Build wheels
+      - name: Build C extension (cibuildwheel for Linux)
         if: runner.os == 'Linux'
         uses: pypa/cibuildwheel@v3.2.1
         with:
           output-dir: dist
           
       - name: Publish to Test PyPI
-        if: runner.os == 'Linux'
         run: |
-          ls dist/*
-          # twine --repository testpypi upload dist/* || { echo "::error:: ❌ Error: Upload failed. Possibly because the version already exists."; exit 1; }
+          twine --repository testpypi upload dist/*.whl || { echo "::error:: ❌ Error: Upload failed. Possibly because the version already exists."; exit 1; }
         env:
           TWINE_USERNAME: __token__
           TWINE_PASSWORD: ${{ secrets.PYPI_TEST_API_TOKEN_ENV }}
